name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.2.2
        id: release
        with:
          release-type: node
          package-name: landing

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
        if: ${{ steps.release.outputs.release_created }}

      - name: Use yarn cache keyed by hashed yarn.lock
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - name: Build app
        run: yarn build
        if: ${{ steps.release.outputs.release_created }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'
          scope: yiphapp
        if: ${{ steps.release.outputs.release_created }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://yiph.app/
        if: ${{ steps.release.outputs.release_created }}
