name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.2.2
        id: release
        with:
          release-type: node
          package-name: landing

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
        if: ${{ steps.release.outputs.release_created }}

      # TODO: Deploy to production

      - name: Update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://yiph.app/
